name: Build and Deploy

on:
  push:
    branches: ["main"]
  #pull_request:
  workflow_dispatch:

jobs:
  build-bicep:
    name: Build Bicep
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Login With OpenID Connect
      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/bicep-deploy@v2
        id: bicep-deploy
        with:
          type: deploymentStack
          operation: create
          name: Development
          location: eastus
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
          resource-group-name: rg-computer-vision-eastus-001
          template-file: ./bicep/main.bicep
          #parameters-file: ./bicep/parameters.json
          action-on-unmanage-resources: delete # Delete unmanaged resources
          deny-settings-mode: none # Allow write and delete operations

      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: "Run app"
        run: |
          # Get the endpoint and key Azure CLI
          AI_SERVICE_ENDPOINT=$(az cognitiveservices account show --name cv-computer-vision-eastus-001 --resource-group rg-computer-vision-eastus-001 --query "properties.endpoint" --output tsv)

          echo "Using endpoint: $AI_SERVICE_ENDPOINT"

          AI_SERVICE_KEY=$(az cognitiveservices account keys list --name cv-computer-vision-eastus-001 --resource-group rg-computer-vision-eastus-001 --query "key1" -o tsv)
          echo "::add-mask::$AI_SERVICE_KEY"

          export AI_SERVICE_ENDPOINT
          export AI_SERVICE_KEY

          dotnet run Analyze.cs
        working-directory: Labfiles/analyze-images
